/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DragBall: typeof import('./src/components/UploadList/DragBall.vue')['default']
    Progress: typeof import('./src/components/UploadList/Progress.vue')['default']
    UploadList: typeof import('./src/components/UploadList/index.vue')['default']
    UploadModal: typeof import('./src/components/UploadList/UploadModal.vue')['default']
    VxeButton: typeof import('vxe-table/es/button/index.js')['VxeButton']
    VxeColumn: typeof import('vxe-table/es/column/index.js')['VxeColumn']
    VxeTable: typeof import('vxe-table/es/table/index.js')['VxeTable']
  }
}
