# sequelize相关
mysql:
  host: 'mysql-container'
  port: 3306
  username: "root"
  password: "12345678"
  database: "upload_file"
  dialect: "mysql"
  synchronize: false
  timezone: "+08:00"
  autoLoadModels: false
  # 打印数据库日志（sequelize）
  logging: false
